
project_id = "uirjyjwzrvqmzdflvyhw"

[auth]
enabled = true

[storage]
enabled = true

[[storage.buckets]]
name = "complaint-attachments"
public = true
file_size_limit = 10485760  # 10MB in bytes
allowed_mime_types = ["image/jpeg", "image/png", "image/gif", "image/webp", "application/pdf", "audio/mp3", "audio/wav", "audio/ogg", "audio/mpeg"]
