
project_id = "uirjyjwzrvqmzdflvyhw"

[storage]
backend = "file"

[storage.buckets]
default = "complaint-attachments"
data_sanitization = "none"
public = true
allowed_mime_types = ["image/jpeg", "image/png", "image/gif", "image/webp", "application/pdf", "audio/mp3", "audio/wav", "audio/ogg", "audio/mpeg"]
